### ISSUE TITLE
Site erroneously marks narrow browser window as "mobile device"

### ISSUE THREAD

**Issue by Tanami** [Athenodoros/TopHat#1]
This is very annoying, especially because you are completely blocked from navigating the site until you resize the window and refresh the whole page.

**Comment by Athenodoros** [comment]
You don't actually need to refresh - it will update as soon as the window size changes.

That said, I think there's [a good reason for the behaviour](https://github.com/Athenodoros/TopHat/blob/main/README.md#potentially-asked-questions): mobile is just a different thing from what this is intended to be at the moment.
