### ISSUE TITLE
Date filter

### ISSUE THREAD

**Issue by oersted** [Athenodoros/TopHat#11]
The date filter in transaction tables is not really usable. The input fields only accept numbers (no "-" or "/" or month names) and the slider below doesn't do anything. I assume it's a generic filter for a numeric field, probably it works with the raw timestamp. A standard date-picker would be best.

Not a very critical issue.

**Comment by Athenodoros** [comment]
It was auto-filling the hyphens in an ISO date, but you're right that it wasn't very intuitive - swapped it out now, for something more explicit.
