### ISSUE TITLE
Button to force update balances

### ISSUE THREAD

**Issue by fastknight** [Athenodoros/TopHat#15]
Is it possible to have a button to force update the Net Worth "value today" ?

The Crypto rates change fast - and its useful to see changes overall multiple times a day. The figure does seem to update, but I'm not entirely sure what triggers it? If I force a currency sync nothing seems to happen to the Net Worth value unfortunately so not sure whats happening.

Thanks for a great tool.

**Comment by Athenodoros** [comment]
The crypto prices are coming from an API that only updates daily, which I think explains the behaviour you're seeing? For the most part I don't really want to rework to use intra-day rates - TopHat is generally oriented around longer-term monitoring and planning, although I realise that crypto's fast moves occupy a weird place in that vision...

**Comment by fastknight** [comment]
That makes sense :) I wondered why it only updated once a day.

Intra-day is fine - it was only when there were really big moves recently that it made any real difference.
