### ISSUE TITLE
Unable to import CSV file

### ISSUE THREAD

**Issue by alonch** [Athenodoros/TopHat#5]
I'm trying to import transactions using the `statement import` section:

* selectthe institution 
* drop the csv file 
* fill separator and date format

Map columns never become enable 😞 
it says `There are files without matching columns`

My bank exports the following column headers
```
"Account Type","Account Number","Transaction Date","Cheque Number","Description 1","Description 2","CAD$","USD$"
```

Any suggestion what may be the problem?

**Comment by Athenodoros** [comment]
Hey @alonch - that error corresponds to the situation where you've imported multiple files, but according to the parsing rules you've set up the different files don't have the same column names. That prevents the column mapping from working properly, so you can't proceed as long as it's the case.

For you, I'd suggest that you check that all of the files are being parsed out to have the same columns - maybe sometimes it's missing CA$/USD$ if there are no transactions in those currencies for a given month, for example?
