### ISSUE TITLE
Manual refresh of exchange rates

### ISSUE THREAD

**Issue by fastknight** [Athenodoros/TopHat#7]
Is there a way to force a manual refresh of exchange rates. The crypto markets are quite fast moving - would be useful if there is a way to manually force a refresh - or add an option to show when they were last updated?

Might also be nice to show the current exchange rates in use somewhere just to verify all looks well. Interface is really nice and am enjoying use this.

Many Thanks!

**Comment by Athenodoros** [comment]
Done! I've added in a button to manually sync currencies, which also tells you the last currency sync time - by default it runs on page load, so I'm expecting that it's fairly up-to-date most of the time anyway. If you want to check the current values, you can do that in the currency dialog: change the sync source to "None" temporarily and you can check the values it's using over time.

Glad you're enjoying it!

**Comment by fastknight** [comment]
Fantastic.

I see the manual sync button and when it last synced - really useful thanks!
